# Generated by Django 3.2.4 on 2021-07-09 16:26

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('tipo_telefono', models.CharField(choices=[('H', 'Casa'), ('C', 'Celular')], default='H', max_length=1)),
                ('telefono_persona', phone_field.models.PhoneField(help_text='Numero tel', max_length=31)),
            ],
            options={
                'db_table': 'tbl_personas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('password_usuario', models.CharField(max_length=500)),
                ('rfc_usuario', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='api.persona')),
            ],
            options={
                'db_table': 'tbl_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('genero_cliente', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('entidad_nacimiento', models.CharField(max_length=100)),
                ('curp_cliente', models.CharField(max_length=100)),
                ('rfc_cliente', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(choices=[('C', 'Casado'), ('S', 'Soltero'), ('D', 'Divorciado')], default='S', max_length=1)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='api.persona')),
            ],
            options={
                'db_table': 'tbl_clientes',
            },
        ),
    ]
