# Generated by Django 3.2.4 on 2021-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientehasgrupo_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientehasgrupo',
            name='rol_grupo',
            field=models.CharField(choices=[('P', 'Presidente'), ('T', 'Tesorera'), ('I', 'Integrante')], default='I', max_length=1),
        ),
    ]
